theme: jekyll-theme-cayman
google-site-verification: nmRCSJERcE1jymwhW1E2Y6p3VnhFJhJDIeyBQcTNHME
title: "Elizabeth Napoleon Paul Portfolio"
description: "Elizabeth Napoleon Paul's front end developer portfolio site"
