theme: jekyll-theme-cayman
google_site_verification: T3hgEfs9A_lck5vWe4zGf27TNs8bvL1X7Z_B1NjbRXM
title: "Elizabeth Napoleon Paul Portfolio"
description: "Elizabeth Napoleon Paul's front end developer portfolio site"
